import React, { useCallback, useEffect, useState } from 'react';
import { BookOpenText, Plus, RefreshCw } from 'lucide-react';
import { createOwnerTopic, listOwnerTopics } from '../api/ownerKnowledgeApi';

export default function OwnerTopicsPage() {
    const [topics, setTopics] = useState([]); const [label, setLabel] = useState(''); const [error, setError] = useState(null); const [busy, setBusy] = useState(false);
    const load = useCallback(async () => { setBusy(true); setError(null); try { setTopics((await listOwnerTopics()).topics || []); } catch (e) { setError(e.message); } finally { setBusy(false); } }, []);
    useEffect(() => { load(); }, [load]);
    const create = async event => { event.preventDefault(); setBusy(true); setError(null); try { await createOwnerTopic(label); setLabel(''); await load(); } catch (e) { setError(e.message); setBusy(false); } };
    return <div className="flow-page max-w-5xl px-1 sm:px-2"><header className="flex items-end justify-between gap-4 pt-5 sm:pt-8 md:pt-12 mb-8"><div><p className="flow-kicker mb-2">獨立知識</p><h1 className="text-3xl sm:text-[2.25rem] font-bold tracking-[-0.05em]">Topics</h1><p className="mt-3 text-sm leading-6 text-[#615d59]">每個 Topic 累積已接受的來源與可追溯知識 revision；它不需要綁定任何 repo。</p></div><button onClick={load} disabled={busy} className="flow-icon-button border notion-whisper-border"><RefreshCw size={16} className={busy ? 'animate-spin' : ''} /></button></header>{error && <p role="alert" className="mb-5 text-sm text-[var(--destructive)]">{error}</p>}<form onSubmit={create} className="flow-panel flex flex-col gap-3 p-5 sm:flex-row"><label className="flex-1 text-sm font-medium">手動建立 Topic<input value={label} onChange={e => setLabel(e.target.value)} required maxLength="120" placeholder="例如：UI UX" className="notion-input mt-2 w-full" /></label><button disabled={busy} className="notion-btn-primary self-end inline-flex items-center gap-2"><Plus size={16} />建立</button></form><section className="mt-7 grid gap-4 md:grid-cols-2">{topics.map(topic => { const revisions = topic.owner_topic_revisions || []; const links = topic.owner_topic_source_links || []; const references = topic.owner_topic_project_references || []; return <article key={topic.id} className="flow-panel p-5"><div className="flex items-start justify-between gap-3"><div><BookOpenText size={18} className="text-[var(--accent)]" /><h2 className="mt-3 text-lg font-bold">{topic.label}</h2></div><span className="text-xs text-[#615d59]">{topic.status}</span></div><p className="mt-3 text-sm text-[#615d59]">{links.length} 個來源連結 · {revisions.length} 個知識 revision · {references.length} 個專案參考</p>{revisions[0] && <p className="mt-4 border-t notion-whisper-border pt-4 text-sm leading-6">{revisions[0].summary}</p>} {!revisions[0] && <p className="mt-4 text-sm text-[#615d59]">尚未有已接受的知識摘要；來源仍會保留為可追溯連結。</p>}</article>; })}</section>{!busy && !topics.length && <p className="mt-8 text-sm text-[#615d59]">還沒有 Topics。從 Focus Mode 接受 Topic 知識候選，或在這裡手動建立。</p>}</div>;
}
