import React, { useState } from 'react';

const TopicCard = ({ topic, domainLabel, onToggleArchive, onRemoveSource, onSave, busy }) => {
    const [editing, setEditing] = useState(false);
    const [draft, setDraft] = useState({ title: topic.title || '', purpose: topic.purpose || '', description: topic.description || '', keywords: (topic.keywords || []).join(', ') });
    const save = async (event) => { event.preventDefault(); await onSave(topic.id, { title: draft.title, purpose: draft.purpose, description: draft.description, keywords: draft.keywords.split(',').map((item) => item.trim()).filter(Boolean) }); setEditing(false); };
    return <article className="notion-card p-5">
        <div className="flex items-start justify-between gap-3"><h4 className="font-semibold text-lg">{topic.title}</h4><div className="flex flex-wrap justify-end gap-2"><span className="notion-badge shrink-0">{topic.status}</span><button type="button" disabled={busy} onClick={() => setEditing((value) => !value)} className="rounded-md border notion-whisper-border px-2 py-1 text-xs text-[#615d59] hover:bg-[var(--surface-muted)] disabled:opacity-50">編輯</button><button type="button" disabled={busy} onClick={() => onToggleArchive(topic)} className="rounded-md border notion-whisper-border px-2 py-1 text-xs text-[#615d59] hover:bg-[var(--surface-muted)] disabled:opacity-50">{topic.status === 'archived' ? '重新啟用' : '封存'}</button></div></div>
        <p className="mt-2 text-xs text-[#615d59]">{topic.project?.title || '尚未遷移的舊主題'} · {domainLabel(topic.domain_key)}</p>
        {editing ? <form onSubmit={save} className="mt-4 space-y-3 rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-muted)] p-3"><label className="block text-xs text-[#615d59]">名稱<input required maxLength="160" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} className="notion-input mt-1 w-full" /></label><label className="block text-xs text-[#615d59]">目的<textarea value={draft.purpose} onChange={(event) => setDraft({ ...draft, purpose: event.target.value })} rows="2" className="notion-input mt-1 w-full resize-y" /></label><label className="block text-xs text-[#615d59]">說明<textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} rows="2" className="notion-input mt-1 w-full resize-y" /></label><label className="block text-xs text-[#615d59]">關鍵字（逗號分隔）<input value={draft.keywords} onChange={(event) => setDraft({ ...draft, keywords: event.target.value })} className="notion-input mt-1 w-full" /></label><div className="flex justify-end gap-2"><button type="button" disabled={busy} onClick={() => setEditing(false)} className="rounded-md border notion-whisper-border px-3 py-1.5 text-xs">取消</button><button type="submit" disabled={busy} className="notion-btn-primary px-3 py-1.5 text-xs">{busy ? '儲存中...' : '儲存修改'}</button></div></form> : <><>{topic.purpose && <p className="mt-3 text-sm text-[#615d59]">{topic.purpose}</p>}{topic.description && <p className="mt-2 text-sm text-[#615d59]/80">{topic.description}</p>}</></>}
        <section className="mt-4 rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-muted)] p-3" aria-label="已接受來源"><div className="flex items-center justify-between gap-2 text-xs font-medium text-[#615d59]"><span>已接受來源</span><span>{topic.accepted_source_count || 0} 篇</span></div>{topic.accepted_sources?.length > 0 ? <div className="mt-3 space-y-2">{topic.accepted_sources.map((source) => <div key={source.id} className="rounded-md bg-white p-2 text-xs"><div className="flex items-start justify-between gap-2"><a href={`/post/${source.id}`} className="font-medium text-[var(--accent)] hover:underline">{source.title || '查看來源貼文'}</a><button type="button" disabled={busy} onClick={() => onRemoveSource(topic.id, source.id)} className="shrink-0 text-[#615d59] hover:text-destructive disabled:opacity-50">移出</button></div>{source.rationale && <p className="mt-1 leading-5 text-[#615d59]">接受理由：{source.rationale}</p>}</div>)}</div> : <p className="mt-2 text-sm text-[#615d59]">尚未接受來源。請從貼文頁選擇「加入主題」，確認建議後再接受。</p>}</section>
        {topic.keywords?.length > 0 && <div className="mt-4 flex flex-wrap gap-1.5">{topic.keywords.map((keyword) => <span key={keyword} className="rounded-md bg-[var(--surface-muted)] px-2 py-1 text-xs text-[#615d59]">#{keyword}</span>)}</div>}
    </article>;
};
export default TopicCard;
